### ISSUE TITLE
 Coms Extensions

### ISSUE THREAD

**Issue by tylerferrara** [NESTLab/2122_MultiDroneIndoorSLAM#44]
# Coms Extensions
These added features will be used for meetings in the state machine

### Ready (or not) to Meet:
Used to start & stop meetings
Format: `ready_to_meet|192.168.0.2|true` or `ready_to_meet|192.168.0.2|false`

### Modify Sync Service:
Send role information in SYNC
Format: `sync|192.168.0.2|relay` or `sync|192.168.0.2|explorer`

### NEXT_MEETING:
```
next_meeting_message includes:
- point: Tuple[int, int, int] (x,y,z)
- time: float
```

Explorer [BROADCAST] -> next_meeting_message
Relay [LISTEN] <- next_meeting_message

```python
return (point, time)
```

### INFO:
```python
return (
  state: str,
  address: str = IP,
  parent: str = IP,
  child: str = IP,
  role: str = "relay | explorer" )
```

---
- [x] Create Ready to Meet Message #47
- [X] Add Role to Sync Messages #46
- [x] Create next meeting service message #48
- [x] Create info service message #49

**Comment by tylerferrara** [comment]
Completed
